-- CertiPass — complete database setup (GENERATED by `npm run build-sql` — edit supabase/migrations instead).
-- Paste this whole file into: Supabase dashboard → SQL Editor → New query → Run.
-- Contents: 20260101000001_schema.sql, 20260101000002_rls.sql, 20260101000003_functions.sql, 20260101000004_reference_data.sql, 20260101000005_email_verification.sql, 20260101000006_username_auth.sql, 20260101000007_role_logins.sql
-- For a brand-new project only.

-- ============================================================================
-- 20260101000001_schema.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — core schema
-- Tables, constraints, indexes and integrity triggers. Row Level Security is
-- defined in 20260101000002_rls.sql, RPCs in 20260101000003_functions.sql.
-- ============================================================================

-- ---------- enums ------------------------------------------------------------
create type public.user_role as enum ('student', 'faculty', 'admin');

create type public.achievement_status as enum (
  'draft',              -- saved by the student, not yet submitted
  'pending',            -- "Pending Verification"
  'verified',
  'rejected',
  'changes_requested'   -- faculty asked the student for corrections
);

create type public.od_status as enum ('pending', 'approved', 'rejected', 'more_info');

-- ---------- shared helpers ---------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------- departments ------------------------------------------------------
create table public.departments (
  id         uuid primary key default gen_random_uuid(),
  code       text not null unique check (char_length(trim(code)) between 1 and 12),
  name       text not null unique check (char_length(trim(name)) between 2 and 120),
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- event categories -------------------------------------------------
create table public.event_categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name        text not null unique check (char_length(trim(name)) between 2 and 60),
  description text,
  sort_order  integer not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ---------- profiles (one row per auth user) ---------------------------------
create table public.profiles (
  id              uuid primary key references auth.users (id) on delete cascade,
  role            public.user_role not null default 'student',
  full_name       text not null check (char_length(trim(full_name)) between 2 and 120),
  email           text not null,
  register_number text,
  faculty_id      text,
  department_id   uuid references public.departments (id) on delete restrict,
  year            smallint check (year between 1 and 6),
  section         text check (section is null or char_length(section) <= 10),
  designation     text,
  phone           text check (phone is null or phone ~ '^[0-9+()\- ]{7,20}$'),
  avatar_url      text,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint profiles_student_has_register_number
    check (role <> 'student' or register_number is not null)
);

create unique index profiles_register_number_key on public.profiles (upper(register_number))
  where register_number is not null;
create unique index profiles_faculty_id_key on public.profiles (upper(faculty_id))
  where faculty_id is not null;
create index profiles_role_department_idx on public.profiles (role, department_id);
create index profiles_full_name_idx on public.profiles (lower(full_name));

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Normalise identifiers so lookups and uniqueness are case-insensitive.
create or replace function public.normalize_profile()
returns trigger
language plpgsql
as $$
begin
  new.email := lower(trim(new.email));
  new.full_name := trim(new.full_name);
  new.register_number := nullif(upper(trim(new.register_number)), '');
  new.faculty_id := nullif(upper(trim(new.faculty_id)), '');
  return new;
end;
$$;

create trigger profiles_normalize
  before insert or update on public.profiles
  for each row execute function public.normalize_profile();

-- ---------- app settings -----------------------------------------------------
create table public.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_by uuid references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now()
);

create trigger app_settings_set_updated_at
  before update on public.app_settings
  for each row execute function public.set_updated_at();

-- ---------- achievements -----------------------------------------------------
create table public.achievements (
  id             uuid primary key default gen_random_uuid(),
  student_id     uuid not null references public.profiles (id) on delete cascade,
  category_id    uuid not null references public.event_categories (id) on delete restrict,
  event_name     text not null check (char_length(trim(event_name)) between 2 and 200),
  organization   text check (organization is null or char_length(organization) <= 200),
  start_date     date not null,
  end_date       date,
  result         text check (result is null or char_length(result) <= 200),
  description    text check (description is null or char_length(description) <= 2000),
  status         public.achievement_status not null default 'draft',
  submitted_at   timestamptz,
  reviewed_by    uuid references public.profiles (id) on delete set null,
  reviewed_at    timestamptz,
  review_comment text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint achievements_dates_ordered check (end_date is null or end_date >= start_date),
  -- Lets child tables prove they belong to the same student as the achievement.
  constraint achievements_id_student_key unique (id, student_id)
);

create index achievements_student_idx on public.achievements (student_id, start_date desc);
create index achievements_status_idx on public.achievements (status, submitted_at);
create index achievements_category_idx on public.achievements (category_id);
create index achievements_start_date_idx on public.achievements (start_date);

create trigger achievements_set_updated_at
  before update on public.achievements
  for each row execute function public.set_updated_at();

-- ---------- certificates -----------------------------------------------------
create table public.certificates (
  id             uuid primary key default gen_random_uuid(),
  achievement_id uuid not null,
  student_id     uuid not null,
  storage_path   text not null unique,
  file_name      text not null check (char_length(file_name) <= 255),
  mime_type      text not null check (mime_type in ('application/pdf', 'image/jpeg', 'image/png')),
  size_bytes     bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  file_hash      text,
  ocr_data       jsonb,
  created_at     timestamptz not null default now(),
  -- exactly one certificate per achievement; owner must match the achievement's owner
  constraint certificates_one_per_achievement unique (achievement_id),
  constraint certificates_achievement_fkey foreign key (achievement_id, student_id)
    references public.achievements (id, student_id) on delete cascade
);

create index certificates_student_hash_idx on public.certificates (student_id, file_hash);

-- ---------- OD requests ------------------------------------------------------
create table public.od_requests (
  id                       uuid primary key default gen_random_uuid(),
  student_id               uuid not null,
  achievement_id           uuid not null,
  category_id              uuid not null references public.event_categories (id) on delete restrict,
  event_name               text not null check (char_length(trim(event_name)) between 2 and 200),
  organization             text check (organization is null or char_length(organization) <= 200),
  event_date               date not null,
  event_end_date           date,
  start_time               time,
  end_time                 time,
  venue                    text not null check (char_length(trim(venue)) between 2 and 200),
  reason                   text not null check (char_length(trim(reason)) between 10 and 1500),
  additional_document_path text,
  additional_document_name text,
  status                   public.od_status not null default 'pending',
  reviewed_by              uuid references public.profiles (id) on delete set null,
  reviewed_at              timestamptz,
  review_comment           text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  constraint od_requests_one_per_achievement unique (achievement_id),
  constraint od_requests_dates_ordered check (event_end_date is null or event_end_date >= event_date),
  constraint od_requests_times_ordered check (
    start_time is null or end_time is null or end_time > start_time
  ),
  constraint od_requests_achievement_fkey foreign key (achievement_id, student_id)
    references public.achievements (id, student_id) on delete restrict
);

create index od_requests_student_idx on public.od_requests (student_id, event_date desc);
create index od_requests_status_idx on public.od_requests (status, created_at);

create trigger od_requests_set_updated_at
  before update on public.od_requests
  for each row execute function public.set_updated_at();

-- ---------- verification records --------------------------------------------
create table public.verification_records (
  id                uuid primary key default gen_random_uuid(),
  achievement_id    uuid not null unique references public.achievements (id) on delete cascade,
  verification_code text not null unique,
  verified_by       uuid references public.profiles (id) on delete set null,
  verified_at       timestamptz not null default now(),
  created_at        timestamptz not null default now()
);

-- ---------- notifications ----------------------------------------------------
create table public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  type       text not null,
  title      text not null,
  message    text,
  link       text,
  is_read    boolean not null default false,
  created_at timestamptz not null default now()
);

create index notifications_user_idx on public.notifications (user_id, is_read, created_at desc);

-- ---------- audit logs -------------------------------------------------------
create table public.audit_logs (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references public.profiles (id) on delete set null,
  action      text not null,
  entity_type text not null,
  entity_id   uuid,
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index audit_logs_created_idx on public.audit_logs (created_at desc);
create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);

-- ============================================================================
-- Role helpers (SECURITY DEFINER so RLS policies can use them without
-- recursing into the profiles policies).
-- ============================================================================
create or replace function public.auth_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and is_active
$$;

create or replace function public.auth_department()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select department_id from public.profiles where id = auth.uid() and is_active
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.auth_role() = 'admin', false)
$$;

-- True when the caller is an active faculty member in the same department as the student.
create or replace function public.is_faculty_of_student(p_student uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles me
    join public.profiles s on s.department_id = me.department_id
    where me.id = auth.uid()
      and me.role = 'faculty'
      and me.is_active
      and s.id = p_student
      and s.role = 'student'
  )
$$;

-- ============================================================================
-- Signup: create the profile row. The role is NEVER read from
-- raw_user_meta_data (which the client controls); only raw_app_meta_data,
-- which can be set only with the service role (admin-create-user function).
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      public.user_role := 'student';
  v_meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_app       jsonb := coalesce(new.raw_app_meta_data, '{}'::jsonb);
  v_domain    text;
  v_open      boolean;
  v_by_admin  boolean := coalesce(v_app ->> 'provisioned', 'false') = 'true';
begin
  if (v_app ->> 'role') in ('faculty', 'admin') then
    v_role := (v_app ->> 'role')::public.user_role;
  end if;

  if v_role = 'student' then
    if not v_by_admin then
      select coalesce((value #>> '{}')::boolean, true) into v_open
        from public.app_settings where key = 'allow_student_registration';
      if v_open is false then
        raise exception 'Student registration is currently closed.';
      end if;
    end if;

    select nullif(trim(value #>> '{}'), '') into v_domain
      from public.app_settings where key = 'student_email_domain';
    if v_domain is not null and lower(new.email) not like '%@' || lower(v_domain) then
      raise exception 'Please register with your college email address (@%).', v_domain;
    end if;
  end if;

  insert into public.profiles (
    id, role, full_name, email, register_number, faculty_id, department_id,
    year, section, designation, phone
  )
  values (
    new.id,
    v_role,
    coalesce(nullif(trim(v_meta ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    new.email,
    case when v_role = 'student' then nullif(trim(v_meta ->> 'register_number'), '') end,
    case when v_role <> 'student' then nullif(trim(v_meta ->> 'faculty_id'), '') end,
    case when v_role <> 'admin' then nullif(v_meta ->> 'department_id', '')::uuid end,
    case when v_role = 'student' then nullif(v_meta ->> 'year', '')::smallint end,
    case when v_role = 'student' then nullif(trim(v_meta ->> 'section'), '') end,
    case when v_role = 'faculty' then nullif(trim(v_meta ->> 'designation'), '') end,
    nullif(trim(v_meta ->> 'phone'), '')
  );

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- Integrity triggers
-- ============================================================================

-- Users may only edit the "soft" parts of their own profile. Identity,
-- role and department are managed by admins. (auth.uid() is null for the
-- service role / SQL editor, which stays unrestricted.)
create or replace function public.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.is_admin() then
    if new.role is distinct from old.role
       or new.email is distinct from old.email
       or new.is_active is distinct from old.is_active
       or new.register_number is distinct from old.register_number
       or new.faculty_id is distinct from old.faculty_id
       or new.department_id is distinct from old.department_id then
      raise exception 'You are not allowed to change role, email, department or identifiers.'
        using errcode = '42501';
    end if;
  end if;
  return new;
end;
$$;

create trigger profiles_protect
  before update on public.profiles
  for each row execute function public.protect_profile_fields();

-- Achievements: students can not forge review data, and a submission needs a certificate.
create or replace function public.guard_achievement_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and public.auth_role() = 'student' then
    new.reviewed_by := old.reviewed_by;
    new.reviewed_at := old.reviewed_at;
    new.review_comment := old.review_comment;
  end if;

  if new.status = 'pending' and old.status is distinct from 'pending' then
    if not exists (select 1 from public.certificates c where c.achievement_id = new.id) then
      raise exception 'Upload a certificate before submitting this achievement.'
        using errcode = 'P0001';
    end if;
    new.submitted_at := now();
  end if;

  return new;
end;
$$;

create trigger achievements_guard_update
  before update on public.achievements
  for each row execute function public.guard_achievement_update();

-- OD requests: students can not forge review data; OD needs a submitted achievement.
create or replace function public.guard_od_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status public.achievement_status;
begin
  if tg_op = 'INSERT' then
    select status into v_status from public.achievements where id = new.achievement_id;
    if v_status is null or v_status not in ('pending', 'verified') then
      raise exception 'Submit the achievement for verification before creating an OD request.'
        using errcode = 'P0001';
    end if;
  elsif auth.uid() is not null and public.auth_role() = 'student' then
    new.student_id := old.student_id;
    new.achievement_id := old.achievement_id;
    new.reviewed_by := old.reviewed_by;
    new.reviewed_at := old.reviewed_at;
    new.review_comment := old.review_comment;
  end if;
  return new;
end;
$$;

create trigger od_requests_guard
  before insert or update on public.od_requests
  for each row execute function public.guard_od_request();

-- ============================================================================
-- Notifications (written by triggers so every code path produces them)
-- ============================================================================
create or replace function public.notify(
  p_user uuid, p_type text, p_title text, p_message text, p_link text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications (user_id, type, title, message, link)
  values (p_user, p_type, p_title, p_message, p_link)
$$;

revoke all on function public.notify(uuid, text, text, text, text) from public, anon, authenticated;

create or replace function public.notify_department_faculty(
  p_student uuid, p_type text, p_title text, p_message text, p_link text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications (user_id, type, title, message, link)
  select f.id, p_type, p_title, p_message, p_link
  from public.profiles s
  join public.profiles f on f.department_id = s.department_id
  where s.id = p_student and f.role = 'faculty' and f.is_active
$$;

revoke all on function public.notify_department_faculty(uuid, text, text, text, text)
  from public, anon, authenticated;

create or replace function public.on_achievement_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  select full_name into v_student from public.profiles where id = new.student_id;

  if new.status = 'pending' then
    perform public.notify(new.student_id, 'achievement_submitted', 'Achievement submitted',
      new.event_name || ' is now pending verification.', '/student/achievements/' || new.id);
    perform public.notify_department_faculty(new.student_id, 'review_requested',
      'New certificate to verify',
      v_student || ' submitted "' || new.event_name || '".', '/faculty/review/' || new.id);
  elsif new.status = 'verified' then
    perform public.notify(new.student_id, 'achievement_verified', 'Certificate verified',
      new.event_name || ' has been verified. Your QR record is ready.',
      '/student/achievements/' || new.id);
  elsif new.status = 'rejected' then
    perform public.notify(new.student_id, 'achievement_rejected', 'Certificate rejected',
      coalesce(new.review_comment, 'Your submission for ' || new.event_name || ' was rejected.'),
      '/student/achievements/' || new.id);
  elsif new.status = 'changes_requested' then
    perform public.notify(new.student_id, 'achievement_changes_requested', 'Changes requested',
      coalesce(new.review_comment, 'Faculty asked for more information on ' || new.event_name || '.'),
      '/student/achievements/' || new.id);
  end if;

  return new;
end;
$$;

create trigger achievements_notify
  after update on public.achievements
  for each row execute function public.on_achievement_status_change();

create or replace function public.on_od_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student text;
begin
  select full_name into v_student from public.profiles where id = new.student_id;

  if tg_op = 'INSERT' then
    perform public.notify(new.student_id, 'od_submitted', 'OD request submitted',
      'Your OD request for ' || new.event_name || ' was submitted for approval.',
      '/student/od/' || new.id);
    perform public.notify_department_faculty(new.student_id, 'review_requested',
      'New OD request', v_student || ' requested OD for "' || new.event_name || '".',
      '/faculty/od/' || new.id);
  elsif new.status is distinct from old.status then
    if new.status = 'pending' then
      perform public.notify_department_faculty(new.student_id, 'review_requested',
        'OD request updated', v_student || ' updated the OD request for "' || new.event_name || '".',
        '/faculty/od/' || new.id);
    elsif new.status = 'approved' then
      perform public.notify(new.student_id, 'od_approved', 'OD approved',
        'Your OD request for ' || new.event_name || ' was approved.', '/student/od/' || new.id);
    elsif new.status = 'rejected' then
      perform public.notify(new.student_id, 'od_rejected', 'OD rejected',
        coalesce(new.review_comment, 'Your OD request for ' || new.event_name || ' was rejected.'),
        '/student/od/' || new.id);
    elsif new.status = 'more_info' then
      perform public.notify(new.student_id, 'od_more_info', 'More information required',
        coalesce(new.review_comment, 'Faculty needs more information about your OD request.'),
        '/student/od/' || new.id);
    end if;
  end if;

  return new;
end;
$$;

create trigger od_requests_notify
  after insert or update on public.od_requests
  for each row execute function public.on_od_change();

-- ============================================================================
-- Audit log (status transitions for workflow tables, every change for admin data)
-- ============================================================================
create or replace function public.audit_workflow_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old jsonb;
  v_new jsonb;
begin
  if tg_op <> 'INSERT' then v_old := to_jsonb(old); end if;
  if tg_op <> 'DELETE' then v_new := to_jsonb(new); end if;

  if tg_op = 'UPDATE' and (v_new ->> 'status') = (v_old ->> 'status') then
    return null;
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    coalesce(v_new ->> 'id', v_old ->> 'id')::uuid,
    jsonb_strip_nulls(jsonb_build_object(
      'from', v_old ->> 'status',
      'to', v_new ->> 'status',
      'event', coalesce(v_new, v_old) ->> 'event_name',
      'comment', v_new ->> 'review_comment'
    ))
  );
  return null;
end;
$$;

create trigger achievements_audit
  after insert or update or delete on public.achievements
  for each row execute function public.audit_workflow_change();

create trigger od_requests_audit
  after insert or update or delete on public.od_requests
  for each row execute function public.audit_workflow_change();

create or replace function public.audit_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
begin
  if tg_op = 'DELETE' then
    v_row := to_jsonb(old);
  else
    v_row := to_jsonb(new);
  end if;

  -- Profile edits by the user themselves are noise; only log changes made by someone else.
  if tg_table_name = 'profiles' and tg_op = 'UPDATE' and auth.uid() = (v_row ->> 'id')::uuid then
    return null;
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    case when v_row ? 'id' then (v_row ->> 'id')::uuid end,
    jsonb_strip_nulls(jsonb_build_object(
      'name', coalesce(v_row ->> 'name', v_row ->> 'full_name', v_row ->> 'key'),
      'role', v_row ->> 'role'
    ))
  );
  return null;
end;
$$;

create trigger departments_audit
  after insert or update or delete on public.departments
  for each row execute function public.audit_admin_change();

create trigger event_categories_audit
  after insert or update or delete on public.event_categories
  for each row execute function public.audit_admin_change();

create trigger app_settings_audit
  after insert or update or delete on public.app_settings
  for each row execute function public.audit_admin_change();

create trigger profiles_audit
  after insert or update on public.profiles
  for each row execute function public.audit_admin_change();


-- ============================================================================
-- 20260101000002_rls.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — Row Level Security
--   student  → only their own records
--   faculty  → submitted records of students in their own department (read-only;
--              decisions go through the SECURITY DEFINER RPCs in the next migration)
--   admin    → everything
-- ============================================================================

alter table public.departments          enable row level security;
alter table public.event_categories     enable row level security;
alter table public.profiles             enable row level security;
alter table public.app_settings         enable row level security;
alter table public.achievements         enable row level security;
alter table public.certificates         enable row level security;
alter table public.od_requests          enable row level security;
alter table public.verification_records enable row level security;
alter table public.notifications        enable row level security;
alter table public.audit_logs           enable row level security;

-- Defence in depth: anonymous visitors get nothing except what is granted below.
revoke all on all tables in schema public from anon;
grant select on public.departments to anon;

-- ---------- departments ------------------------------------------------------
create policy departments_read on public.departments
  for select to anon, authenticated
  using (is_active or public.is_admin());

create policy departments_admin_write on public.departments
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------- event categories -------------------------------------------------
create policy categories_read on public.event_categories
  for select to authenticated
  using (is_active or public.is_admin());

create policy categories_admin_write on public.event_categories
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------- profiles ---------------------------------------------------------
create policy profiles_select on public.profiles
  for select to authenticated
  using (
    id = auth.uid()
    or public.is_admin()
    or (
      role = 'student'
      and public.auth_role() = 'faculty'
      and department_id is not distinct from public.auth_department()
    )
  );

-- Sensitive columns are additionally locked by the profiles_protect trigger.
create policy profiles_update on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- Rows are created by the signup trigger; accounts are deactivated (is_active), not deleted.

-- ---------- app settings -----------------------------------------------------
create policy settings_admin_read on public.app_settings
  for select to authenticated
  using (public.is_admin());

create policy settings_admin_write on public.app_settings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------- achievements -----------------------------------------------------
create policy achievements_select on public.achievements
  for select to authenticated
  using (
    student_id = auth.uid()
    or public.is_admin()
    or (status <> 'draft' and public.is_faculty_of_student(student_id))
  );

create policy achievements_student_insert on public.achievements
  for insert to authenticated
  with check (
    student_id = auth.uid()
    and public.auth_role() = 'student'
    and status = 'draft'
  );

-- Pending items are locked while faculty review them; verified items are immutable.
create policy achievements_student_update on public.achievements
  for update to authenticated
  using (
    student_id = auth.uid()
    and public.auth_role() = 'student'
    and status in ('draft', 'changes_requested', 'rejected')
  )
  with check (
    student_id = auth.uid()
    -- never 'verified': only the review RPCs can certify a record
    and status in ('draft', 'pending', 'changes_requested', 'rejected')
  );

create policy achievements_student_delete on public.achievements
  for delete to authenticated
  using (
    student_id = auth.uid()
    and status in ('draft', 'changes_requested', 'rejected')
  );

create policy achievements_admin_delete on public.achievements
  for delete to authenticated
  using (public.is_admin());

-- ---------- certificates -----------------------------------------------------
create or replace function public.achievement_is_editable(p_achievement uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.achievements a
    where a.id = p_achievement
      and a.student_id = auth.uid()
      and a.status in ('draft', 'changes_requested', 'rejected')
  )
$$;

create policy certificates_select on public.certificates
  for select to authenticated
  using (
    student_id = auth.uid()
    or public.is_admin()
    or (
      public.is_faculty_of_student(student_id)
      and exists (
        select 1 from public.achievements a
        where a.id = achievement_id and a.status <> 'draft'
      )
    )
  );

create policy certificates_student_insert on public.certificates
  for insert to authenticated
  with check (student_id = auth.uid() and public.achievement_is_editable(achievement_id));

create policy certificates_student_update on public.certificates
  for update to authenticated
  using (student_id = auth.uid() and public.achievement_is_editable(achievement_id))
  with check (student_id = auth.uid() and public.achievement_is_editable(achievement_id));

create policy certificates_student_delete on public.certificates
  for delete to authenticated
  using (student_id = auth.uid() and public.achievement_is_editable(achievement_id));

-- ---------- OD requests ------------------------------------------------------
create policy od_select on public.od_requests
  for select to authenticated
  using (
    student_id = auth.uid()
    or public.is_admin()
    or public.is_faculty_of_student(student_id)
  );

create policy od_student_insert on public.od_requests
  for insert to authenticated
  with check (
    student_id = auth.uid()
    and public.auth_role() = 'student'
    and status = 'pending'
  );

-- Students can only edit a request after faculty asked for more information.
create policy od_student_update on public.od_requests
  for update to authenticated
  using (student_id = auth.uid() and status = 'more_info')
  with check (student_id = auth.uid() and status in ('more_info', 'pending'));

create policy od_student_delete on public.od_requests
  for delete to authenticated
  using (student_id = auth.uid() and status in ('pending', 'more_info'));

create policy od_admin_delete on public.od_requests
  for delete to authenticated
  using (public.is_admin());

-- ---------- verification records ---------------------------------------------
-- Visibility follows the achievement (the sub-select is itself filtered by RLS).
create policy verification_select on public.verification_records
  for select to authenticated
  using (exists (select 1 from public.achievements a where a.id = achievement_id));

-- ---------- notifications ----------------------------------------------------
create policy notifications_select on public.notifications
  for select to authenticated
  using (user_id = auth.uid());

create policy notifications_update on public.notifications
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy notifications_delete on public.notifications
  for delete to authenticated
  using (user_id = auth.uid());

-- Users may only flip the read flag; everything else is written by triggers.
revoke update on public.notifications from authenticated;
grant update (is_read) on public.notifications to authenticated;

-- ---------- audit logs -------------------------------------------------------
create policy audit_admin_read on public.audit_logs
  for select to authenticated
  using (public.is_admin());

-- ============================================================================
-- Reporting views — security_invoker means the caller's RLS applies, so
-- faculty only ever see their department.
-- ============================================================================
create or replace view public.achievement_details
with (security_invoker = true) as
select
  a.id,
  a.student_id,
  a.category_id,
  a.event_name,
  a.organization,
  a.start_date,
  a.end_date,
  a.result,
  a.description,
  a.status,
  a.submitted_at,
  a.reviewed_at,
  a.review_comment,
  a.created_at,
  s.full_name       as student_name,
  s.register_number as register_number,
  s.year            as student_year,
  s.section         as student_section,
  s.department_id   as department_id,
  d.name            as department_name,
  d.code            as department_code,
  c.name            as category_name,
  c.slug            as category_slug,
  v.verification_code,
  v.verified_at,
  (select od.status from public.od_requests od where od.achievement_id = a.id) as od_status
from public.achievements a
join public.profiles s on s.id = a.student_id
left join public.departments d on d.id = s.department_id
join public.event_categories c on c.id = a.category_id
left join public.verification_records v on v.achievement_id = a.id;

create or replace view public.od_details
with (security_invoker = true) as
select
  o.id,
  o.student_id,
  o.achievement_id,
  o.category_id,
  o.event_name,
  o.organization,
  o.event_date,
  o.event_end_date,
  o.start_time,
  o.end_time,
  o.venue,
  o.reason,
  o.additional_document_path,
  o.additional_document_name,
  o.status,
  o.reviewed_at,
  o.review_comment,
  o.created_at,
  o.updated_at,
  s.full_name       as student_name,
  s.register_number as register_number,
  s.year            as student_year,
  s.department_id   as department_id,
  d.name            as department_name,
  c.name            as category_name,
  a.status          as achievement_status
from public.od_requests o
join public.profiles s on s.id = o.student_id
left join public.departments d on d.id = s.department_id
join public.event_categories c on c.id = o.category_id
join public.achievements a on a.id = o.achievement_id;

-- One row per student with participation counts, for the faculty / admin directories.
create or replace view public.student_summaries
with (security_invoker = true) as
select
  p.id,
  p.full_name,
  p.email,
  p.register_number,
  p.year,
  p.section,
  p.phone,
  p.avatar_url,
  p.is_active,
  p.department_id,
  d.name as department_name,
  d.code as department_code,
  p.created_at,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status <> 'draft') as total_achievements,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status = 'verified') as verified_achievements,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status = 'pending') as pending_achievements,
  (select count(*) from public.od_requests o where o.student_id = p.id) as total_ods,
  (select count(*) from public.od_requests o where o.student_id = p.id and o.status = 'approved') as approved_ods
from public.profiles p
left join public.departments d on d.id = p.department_id
where p.role = 'student';

grant select on public.achievement_details, public.od_details, public.student_summaries to authenticated;

-- ============================================================================
-- Storage
-- ============================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('certificates', 'certificates', false, 10485760,
    array['application/pdf', 'image/jpeg', 'image/png']),
  ('avatars', 'avatars', true, 2097152,
    array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
  set file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types,
      public = excluded.public;

-- A stored file is "locked" while it backs a submitted record, so students
-- can not delete or swap evidence that faculty are reviewing or have verified.
create or replace function public.storage_object_locked(p_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.certificates c
    join public.achievements a on a.id = c.achievement_id
    where c.storage_path = p_path and a.status in ('pending', 'verified')
  ) or exists (
    select 1 from public.od_requests o
    where o.additional_document_path = p_path and o.status in ('pending', 'approved')
  )
$$;

-- Faculty may read files that belong to a submitted (non-draft) record of a student in their department.
create or replace function public.faculty_can_read_object(p_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.certificates c
    join public.achievements a on a.id = c.achievement_id
    where c.storage_path = p_path
      and a.status <> 'draft'
      and public.is_faculty_of_student(c.student_id)
  ) or exists (
    select 1 from public.od_requests o
    where o.additional_document_path = p_path
      and public.is_faculty_of_student(o.student_id)
  )
$$;

create policy certificates_files_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'certificates'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.auth_role() = 'student'
  );

create policy certificates_files_student_read on storage.objects
  for select to authenticated
  using (bucket_id = 'certificates' and (storage.foldername(name))[1] = auth.uid()::text);

create policy certificates_files_staff_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'certificates'
    and (public.is_admin() or public.faculty_can_read_object(name))
  );

create policy certificates_files_student_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'certificates'
    and (storage.foldername(name))[1] = auth.uid()::text
    and not public.storage_object_locked(name)
  );

create policy avatars_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy avatars_update on storage.objects
  for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy avatars_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- ============================================================================
-- Realtime: live notification badge
-- ============================================================================
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
     ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end
$$;


-- ============================================================================
-- 20260101000003_functions.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — RPC functions
-- Faculty decisions are made exclusively through these functions so every
-- transition is validated (department scope, current state, required reason)
-- and atomic. Triggers in the schema migration create notifications + audit rows.
-- ============================================================================

-- ---------- public (anon-safe) -----------------------------------------------

-- Whitelisted settings the login / registration / verification pages need.
create or replace function public.public_settings()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb)
  from public.app_settings
  where key in ('institution_name', 'student_email_domain', 'allow_student_registration')
$$;

-- Lets the registration form tell the student early that a register number is taken.
create or replace function public.register_number_available(p_register_number text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles where upper(register_number) = upper(trim(p_register_number))
  )
$$;

-- Public QR landing page. Returns ONLY fields that are appropriate to share:
-- no email, phone, internal ids or reviewer identity.
create or replace function public.get_public_verification(p_code text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'verification_code', v.verification_code,
    'verified_at', v.verified_at,
    'student_name', s.full_name,
    'department', d.name,
    'event_name', a.event_name,
    'category', c.name,
    'organization', a.organization,
    'result', a.result,
    'start_date', a.start_date,
    'end_date', a.end_date,
    'institution', (select value #>> '{}' from public.app_settings where key = 'institution_name')
  )
  from public.verification_records v
  join public.achievements a on a.id = v.achievement_id and a.status = 'verified'
  join public.profiles s on s.id = a.student_id
  join public.event_categories c on c.id = a.category_id
  left join public.departments d on d.id = s.department_id
  where v.verification_code = upper(trim(p_code))
$$;

grant execute on function public.public_settings() to anon, authenticated;
grant execute on function public.register_number_available(text) to anon, authenticated;
grant execute on function public.get_public_verification(text) to anon, authenticated;

-- ---------- verification code ------------------------------------------------
create or replace function public.generate_verification_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  -- no I, O, 0, 1 — easy to read aloud and to type from a printout
  v_alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_prefix   text;
  v_bytes    bytea;
  v_code     text;
  i          int;
begin
  select coalesce(nullif(trim(value #>> '{}'), ''), 'CP') into v_prefix
    from public.app_settings where key = 'verification_prefix';
  v_prefix := coalesce(v_prefix, 'CP');

  loop
    v_bytes := decode(replace(gen_random_uuid()::text, '-', ''), 'hex');
    v_code := '';
    for i in 0..4 loop
      -- 256 is a multiple of 32, so the modulo introduces no bias
      v_code := v_code || substr(v_alphabet, (get_byte(v_bytes, i) % 32) + 1, 1);
    end loop;
    v_code := upper(v_prefix) || '-' || to_char(now(), 'YYYY') || '-' || v_code;
    exit when not exists (select 1 from public.verification_records where verification_code = v_code);
  end loop;

  return v_code;
end;
$$;

revoke all on function public.generate_verification_code() from public, anon, authenticated;

-- ---------- faculty decisions ------------------------------------------------
create or replace function public.verify_achievement(p_achievement_id uuid, p_comment text default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  a      public.achievements;
  v_code text;
begin
  select * into a from public.achievements where id = p_achievement_id for update;
  if not found then
    raise exception 'Achievement not found.' using errcode = 'P0002';
  end if;
  if not public.is_faculty_of_student(a.student_id) then
    raise exception 'You can only review students in your department.' using errcode = '42501';
  end if;
  if a.status <> 'pending' then
    raise exception 'Only submissions that are pending verification can be verified.' using errcode = 'P0001';
  end if;

  v_code := public.generate_verification_code();

  update public.achievements
     set status = 'verified',
         reviewed_by = auth.uid(),
         reviewed_at = now(),
         review_comment = nullif(trim(p_comment), '')
   where id = a.id;

  insert into public.verification_records (achievement_id, verification_code, verified_by)
  values (a.id, v_code, auth.uid());

  return v_code;
end;
$$;

create or replace function public.reject_achievement(p_achievement_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  a public.achievements;
begin
  if char_length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Please give the student a reason for the rejection.' using errcode = 'P0001';
  end if;

  select * into a from public.achievements where id = p_achievement_id for update;
  if not found then
    raise exception 'Achievement not found.' using errcode = 'P0002';
  end if;
  if not public.is_faculty_of_student(a.student_id) then
    raise exception 'You can only review students in your department.' using errcode = '42501';
  end if;
  if a.status <> 'pending' then
    raise exception 'Only submissions that are pending verification can be rejected.' using errcode = 'P0001';
  end if;

  update public.achievements
     set status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now(),
         review_comment = trim(p_reason)
   where id = a.id;
end;
$$;

create or replace function public.request_achievement_changes(p_achievement_id uuid, p_message text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  a public.achievements;
begin
  if char_length(trim(coalesce(p_message, ''))) < 5 then
    raise exception 'Please tell the student what needs to change.' using errcode = 'P0001';
  end if;

  select * into a from public.achievements where id = p_achievement_id for update;
  if not found then
    raise exception 'Achievement not found.' using errcode = 'P0002';
  end if;
  if not public.is_faculty_of_student(a.student_id) then
    raise exception 'You can only review students in your department.' using errcode = '42501';
  end if;
  if a.status <> 'pending' then
    raise exception 'Only submissions that are pending verification can be sent back.' using errcode = 'P0001';
  end if;

  update public.achievements
     set status = 'changes_requested', reviewed_by = auth.uid(), reviewed_at = now(),
         review_comment = trim(p_message)
   where id = a.id;
end;
$$;

create or replace function public.review_od_request(
  p_od_id uuid, p_decision public.od_status, p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.od_requests;
begin
  if p_decision not in ('approved', 'rejected', 'more_info') then
    raise exception 'Invalid decision.' using errcode = 'P0001';
  end if;
  if p_decision in ('rejected', 'more_info') and char_length(trim(coalesce(p_comment, ''))) < 5 then
    raise exception 'Please add a comment so the student knows what to do next.' using errcode = 'P0001';
  end if;

  select * into o from public.od_requests where id = p_od_id for update;
  if not found then
    raise exception 'OD request not found.' using errcode = 'P0002';
  end if;
  if not public.is_faculty_of_student(o.student_id) then
    raise exception 'You can only review students in your department.' using errcode = '42501';
  end if;
  if o.status <> 'pending' then
    raise exception 'This OD request has already been reviewed.' using errcode = 'P0001';
  end if;

  update public.od_requests
     set status = p_decision, reviewed_by = auth.uid(), reviewed_at = now(),
         review_comment = nullif(trim(p_comment), '')
   where id = o.id;
end;
$$;

revoke all on function public.verify_achievement(uuid, text) from public, anon;
revoke all on function public.reject_achievement(uuid, text) from public, anon;
revoke all on function public.request_achievement_changes(uuid, text) from public, anon;
revoke all on function public.review_od_request(uuid, public.od_status, text) from public, anon;
grant execute on function public.verify_achievement(uuid, text) to authenticated;
grant execute on function public.reject_achievement(uuid, text) to authenticated;
grant execute on function public.request_achievement_changes(uuid, text) to authenticated;
grant execute on function public.review_od_request(uuid, public.od_status, text) to authenticated;

-- ---------- dashboards -------------------------------------------------------
-- SECURITY INVOKER (default): counts are scoped by the caller's RLS, so the same
-- function serves a faculty member (their department) and an admin (everything).
create or replace function public.review_stats(p_since timestamptz default date_trunc('day', now()))
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'pending_certificates', (select count(*) from public.achievements where status = 'pending'),
    'pending_ods',          (select count(*) from public.od_requests where status = 'pending'),
    'verified_today',       (select count(*) from public.achievements
                              where status = 'verified' and reviewed_at >= p_since),
    'verified_total',       (select count(*) from public.achievements where status = 'verified'),
    'rejected',             (select count(*) from public.achievements where status = 'rejected'),
    'total_students',       (select count(*) from public.profiles where role = 'student'),
    'total_faculty',        (select count(*) from public.profiles where role = 'faculty'),
    'total_achievements',   (select count(*) from public.achievements where status <> 'draft'),
    'total_ods',            (select count(*) from public.od_requests),
    'approved_ods',         (select count(*) from public.od_requests where status = 'approved'),
    'rejected_ods',         (select count(*) from public.od_requests where status = 'rejected')
  )
$$;

grant execute on function public.review_stats(timestamptz) to authenticated;


-- ============================================================================
-- 20260101000004_reference_data.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — reference data (safe to re-run)
-- ============================================================================

insert into public.departments (code, name) values
  ('CSE',  'Computer Science and Engineering'),
  ('IT',   'Information Technology'),
  ('ECE',  'Electronics and Communication Engineering'),
  ('EEE',  'Electrical and Electronics Engineering'),
  ('MECH', 'Mechanical Engineering'),
  ('CIVIL','Civil Engineering'),
  ('AIDS', 'Artificial Intelligence and Data Science'),
  ('CSBS', 'Computer Science and Business Systems')
on conflict (code) do nothing;

insert into public.event_categories (slug, name, description, sort_order) values
  ('hackathon',          'Hackathon',          'Time-boxed build events and ideathons',              10),
  ('workshop',           'Workshop',           'Hands-on training sessions and bootcamps',           20),
  ('symposium',          'Symposium',          'Inter-college technical and cultural symposiums',    30),
  ('internship',         'Internship',         'Industry or research internships',                   40),
  ('conference',         'Conference',         'Conference attendance and talks',                    50),
  ('competition',        'Competition',        'Contests, quizzes, sports and design challenges',    60),
  ('paper-presentation', 'Paper Presentation', 'Technical paper and poster presentations',           70),
  ('certification',      'Certification',      'Online or professional course certifications',       80),
  ('club-activity',      'Club Activity',      'Student chapters, clubs and volunteering',           90),
  ('other',              'Other',              'Anything that does not fit the categories above',   100)
on conflict (slug) do nothing;

insert into public.app_settings (key, value) values
  ('institution_name',           to_jsonb('Your College'::text)),
  ('student_email_domain',       to_jsonb(''::text)),
  ('allow_student_registration', to_jsonb(true)),
  ('verification_prefix',        to_jsonb('CP'::text))
on conflict (key) do nothing;


-- ============================================================================
-- 20260101000005_email_verification.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — e-mail verification support
--
-- Problem: signing up creates the profile immediately (with the register number), but the account stays
-- unverified until the e-mail link is clicked. If the student mistyped their address, the verification mail
-- never arrives AND the register number is now "taken" by an account nobody can ever sign in to, so they could
-- not simply register again with the right address.
--
-- Fix: an *unconfirmed* sign-up never holds a register number. A new sign-up with the same register number
-- replaces it, and the availability check treats it as free. A confirmed account is never touched.
-- ============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      public.user_role := 'student';
  v_meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_app       jsonb := coalesce(new.raw_app_meta_data, '{}'::jsonb);
  v_domain    text;
  v_open      boolean;
  v_by_admin  boolean := coalesce(v_app ->> 'provisioned', 'false') = 'true';
  v_register  text;
begin
  if (v_app ->> 'role') in ('faculty', 'admin') then
    v_role := (v_app ->> 'role')::public.user_role;
  end if;

  if v_role = 'student' then
    if not v_by_admin then
      select coalesce((value #>> '{}')::boolean, true) into v_open
        from public.app_settings where key = 'allow_student_registration';
      if v_open is false then
        raise exception 'Student registration is currently closed.';
      end if;
    end if;

    select nullif(trim(value #>> '{}'), '') into v_domain
      from public.app_settings where key = 'student_email_domain';
    if v_domain is not null and lower(new.email) not like '%@' || lower(v_domain) then
      raise exception 'Please register with your college email address (@%).', v_domain;
    end if;

    -- Release the register number from an earlier sign-up that never verified its e-mail address.
    v_register := nullif(trim(v_meta ->> 'register_number'), '');
    if v_register is not null then
      delete from auth.users u
       using public.profiles p
       where p.id = u.id
         and u.id <> new.id
         and u.email_confirmed_at is null
         and upper(p.register_number) = upper(v_register);
    end if;
  end if;

  insert into public.profiles (
    id, role, full_name, email, register_number, faculty_id, department_id,
    year, section, designation, phone
  )
  values (
    new.id,
    v_role,
    coalesce(nullif(trim(v_meta ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    new.email,
    case when v_role = 'student' then v_register end,
    case when v_role <> 'student' then nullif(trim(v_meta ->> 'faculty_id'), '') end,
    case when v_role <> 'admin' then nullif(v_meta ->> 'department_id', '')::uuid end,
    case when v_role = 'student' then nullif(v_meta ->> 'year', '')::smallint end,
    case when v_role = 'student' then nullif(trim(v_meta ->> 'section'), '') end,
    case when v_role = 'faculty' then nullif(trim(v_meta ->> 'designation'), '') end,
    nullif(trim(v_meta ->> 'phone'), '')
  );

  return new;
end;
$$;

-- "Is this register number free?" — only a *confirmed* account counts as holding it.
create or replace function public.register_number_available(p_register_number text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1
    from public.profiles p
    join auth.users u on u.id = p.id
    where upper(p.register_number) = upper(trim(p_register_number))
      and u.email_confirmed_at is not null
  )
$$;

grant execute on function public.register_number_available(text) to anon, authenticated;


-- ============================================================================
-- 20260101000006_username_auth.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — username sign-in for students (no e-mail verification)
--
-- Students sign in with a USERNAME + password. Supabase Auth needs an e-mail-shaped identity, so each student's
-- login identity is derived from the username:  <username>@certipass.invalid
-- (a username may itself look like an e-mail address, e.g. dinesh.g.2024.aids@rajalakshmi.edu.in; its "@" is written
-- "+" in the login address so the result is always one valid address — usernames can never contain "+")
-- (".invalid" is a reserved TLD that can never resolve, so nothing is ever delivered and no real person's address
-- is involved). That address is internal: it is NOT stored in the profile and is never shown in the app.
-- Faculty and admins keep signing in with their real e-mail address.
--
-- Safe to run on a project that already has migrations 1–5 (existing rows are kept and backfilled).
-- ============================================================================

-- ---------- 1. profile columns -------------------------------------------------------------------------------------
alter table public.profiles add column if not exists username text;
-- students no longer have a (real) e-mail on file; staff still do
alter table public.profiles alter column email drop not null;

-- ---------- 2. give every existing student a username ---------------------------------------------------------------
do $$
declare
  r         record;
  base      text;
  candidate text;
  n         integer;
begin
  for r in
    select id, register_number, email from public.profiles
    where role = 'student' and username is null
    order by created_at
  loop
    base := lower(regexp_replace(
      coalesce(r.register_number, nullif(split_part(coalesce(r.email, ''), '@', 1), ''), 'student'),
      '[^a-zA-Z0-9]+', '', 'g'));
    if length(base) < 3 then
      base := 'student' || substr(replace(r.id::text, '-', ''), 1, 6);
    end if;
    base := substr(base, 1, 26);
    candidate := base;
    n := 1;
    while exists (select 1 from public.profiles where username = candidate) loop
      n := n + 1;
      candidate := base || n::text;
    end loop;
    update public.profiles set username = candidate where id = r.id;
  end loop;
end
$$;

-- ---------- 3. username rules: format, required for students, unique ---------------------------------------------------
-- (drop-then-add, so running this file again — for example to pick up a changed username rule — is safe)
alter table public.profiles drop constraint if exists profiles_username_format;
alter table public.profiles
  add constraint profiles_username_format
  check (username is null or username ~ '^(?=.{3,100}$)(?!.*\.\.)[a-z0-9]([a-z0-9._-]*[a-z0-9])?(@[a-z0-9]([a-z0-9._-]*[a-z0-9])?)?$');

alter table public.profiles drop constraint if exists profiles_student_has_username;
alter table public.profiles
  add constraint profiles_student_has_username
  check (role <> 'student' or username is not null);

create unique index if not exists profiles_username_key on public.profiles (username) where username is not null;

create or replace function public.normalize_profile()
returns trigger
language plpgsql
as $$
begin
  new.email := nullif(lower(trim(new.email)), '');
  new.username := nullif(lower(trim(new.username)), '');
  new.full_name := trim(new.full_name);
  new.register_number := nullif(upper(trim(new.register_number)), '');
  new.faculty_id := nullif(upper(trim(new.faculty_id)), '');
  return new;
end;
$$;

-- The username IS the login identity: the sign-in address is derived from it, so renaming a profile would silently
-- lock the student out. Nobody can change it through the API (not even admins); only the service role / SQL editor.
create or replace function public.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null then
    if new.username is distinct from old.username then
      raise exception 'A username can not be changed.' using errcode = '42501';
    end if;
    if not public.is_admin() and (
         new.role is distinct from old.role
         or new.email is distinct from old.email
         or new.is_active is distinct from old.is_active
         or new.register_number is distinct from old.register_number
         or new.faculty_id is distinct from old.faculty_id
         or new.department_id is distinct from old.department_id
       ) then
      raise exception 'You are not allowed to change role, email, department or identifiers.'
        using errcode = '42501';
    end if;
  end if;
  return new;
end;
$$;

-- Names that look official can't be claimed by a student. (Keep in sync with RESERVED_USERNAMES in src/lib/identity.ts.)
create or replace function public.is_reserved_username(p_username text)
returns boolean
language sql
immutable
as $$
  select lower(trim(p_username)) in (
    'admin', 'administrator', 'root', 'faculty', 'staff', 'support', 'certipass', 'system', 'moderator', 'help'
  )
$$;

-- ---------- 4. sign-up trigger ---------------------------------------------------------------------------------------
-- The role still comes only from app_metadata (service role), never from what the browser sends.
-- A student sign-up must carry a valid username AND its login address must be exactly <username>@certipass.invalid,
-- so a public sign-up can never register an arbitrary (e.g. someone else's real) e-mail address.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      public.user_role := 'student';
  v_meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_app       jsonb := coalesce(new.raw_app_meta_data, '{}'::jsonb);
  v_open      boolean;
  v_by_admin  boolean := coalesce(v_app ->> 'provisioned', 'false') = 'true';
  v_username  text;
  -- must match INTERNAL_EMAIL_DOMAIN in src/lib/identity.ts and the admin-create-user function
  v_internal_domain constant text := 'certipass.invalid';
begin
  if (v_app ->> 'role') in ('faculty', 'admin') then
    v_role := (v_app ->> 'role')::public.user_role;
  end if;

  if v_role = 'student' then
    if not v_by_admin then
      select coalesce((value #>> '{}')::boolean, true) into v_open
        from public.app_settings where key = 'allow_student_registration';
      if v_open is false then
        raise exception 'Student registration is currently closed.';
      end if;
    end if;

    v_username := lower(trim(coalesce(v_meta ->> 'username', '')));
    if v_username !~ '^(?=.{3,100}$)(?!.*\.\.)[a-z0-9]([a-z0-9._-]*[a-z0-9])?(@[a-z0-9]([a-z0-9._-]*[a-z0-9])?)?$' then
      raise exception 'Choose a username of 3 to 100 characters: letters, numbers, dots, dashes, underscores and at most one @.';
    end if;
    if public.is_reserved_username(v_username) then
      raise exception 'That username is reserved. Please choose another.';
    end if;
    -- the "@" of an e-mail-style username is written "+" in the login address (usernames can't contain "+")
    if lower(coalesce(new.email, '')) <> replace(v_username, '@', '+') || '@' || v_internal_domain then
      raise exception 'Invalid sign-up request.';
    end if;
  end if;

  insert into public.profiles (
    id, role, username, full_name, email, register_number, faculty_id, department_id,
    year, section, designation, phone
  )
  values (
    new.id,
    v_role,
    case when v_role = 'student' then v_username end,
    coalesce(nullif(trim(v_meta ->> 'full_name'), ''), v_username, split_part(new.email, '@', 1)),
    case when v_role = 'student' then null else new.email end, -- the internal login address is never stored for students
    case when v_role = 'student' then nullif(trim(v_meta ->> 'register_number'), '') end,
    case when v_role <> 'student' then nullif(trim(v_meta ->> 'faculty_id'), '') end,
    case when v_role <> 'admin' then nullif(v_meta ->> 'department_id', '')::uuid end,
    case when v_role = 'student' then nullif(v_meta ->> 'year', '')::smallint end,
    case when v_role = 'student' then nullif(trim(v_meta ->> 'section'), '') end,
    case when v_role = 'faculty' then nullif(trim(v_meta ->> 'designation'), '') end,
    nullif(trim(v_meta ->> 'phone'), '')
  );

  return new;
end;
$$;

-- ---------- 5. availability checks (used by the registration form) -------------------------------------------------------
create or replace function public.username_available(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not public.is_reserved_username(p_username)
     and not exists (select 1 from public.profiles where username = lower(trim(p_username)))
$$;

-- back to the plain rule: every account is verified-by-construction, so any holder of the number counts
create or replace function public.register_number_available(p_register_number text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles where upper(register_number) = upper(trim(p_register_number))
  )
$$;

grant execute on function public.username_available(text) to anon, authenticated;
grant execute on function public.register_number_available(text) to anon, authenticated;

-- ---------- 6. settings: students no longer have a college e-mail to restrict -----------------------------------------
delete from public.app_settings where key = 'student_email_domain';

create or replace function public.public_settings()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb)
  from public.app_settings
  where key in ('institution_name', 'allow_student_registration')
$$;

grant execute on function public.public_settings() to anon, authenticated;

-- ---------- 7. staff directory view: username instead of e-mail ------------------------------------------------------
drop view if exists public.student_summaries;

create view public.student_summaries
with (security_invoker = true) as
select
  p.id,
  p.full_name,
  p.username,
  p.register_number,
  p.year,
  p.section,
  p.phone,
  p.avatar_url,
  p.is_active,
  p.department_id,
  d.name as department_name,
  d.code as department_code,
  p.created_at,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status <> 'draft') as total_achievements,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status = 'verified') as verified_achievements,
  (select count(*) from public.achievements a where a.student_id = p.id and a.status = 'pending') as pending_achievements,
  (select count(*) from public.od_requests o where o.student_id = p.id) as total_ods,
  (select count(*) from public.od_requests o where o.student_id = p.id and o.status = 'approved') as approved_ods
from public.profiles p
left join public.departments d on d.id = p.department_id
where p.role = 'student';

revoke all on public.student_summaries from anon;
grant select on public.student_summaries to authenticated;


-- ============================================================================
-- 20260101000007_role_logins.sql
-- ============================================================================

-- ============================================================================
-- CertiPass — username sign-in for ALL three roles (student, faculty, admin)
--
-- Migration 6 gave students a username. This extends the same model to faculty and admins so every role signs in
-- with Username + Password and there is no e-mail anywhere in the sign-in flow:
--   * every profile has a username (required, unique, immutable);
--   * every NEW account's login identity is <username>@certipass.invalid (an "@" in the username is written "+");
--   * a public sign-up can only ever create a student — faculty come from an administrator (edge function) and the
--     first administrator from `npm run create-admin`; the role is read only from app_metadata (service role).
--
-- Safe to run on a project that already has migrations 1–6, and safe to run again.
-- ============================================================================

-- ---------- 1. give every existing faculty / admin a username -----------------------------------------------------------
-- (their *login* is converted separately by `npm run convert-staff`; nothing here touches auth.users)
do $$
declare
  r         record;
  base      text;
  candidate text;
  n         integer;
begin
  for r in
    select id, role, email, faculty_id from public.profiles
    where username is null
    order by created_at
  loop
    base := lower(regexp_replace(
      coalesce(nullif(split_part(coalesce(r.email, ''), '@', 1), ''), r.faculty_id, r.role::text),
      '[^a-zA-Z0-9]+', '.', 'g'));
    base := trim(both '.' from base);
    if length(base) < 3 then
      base := r.role::text || substr(replace(r.id::text, '-', ''), 1, 6);
    end if;
    base := substr(base, 1, 26);
    base := trim(both '.' from base);
    candidate := base;
    n := 1;
    while exists (select 1 from public.profiles where username = candidate) loop
      n := n + 1;
      candidate := base || n::text;
    end loop;
    update public.profiles set username = candidate where id = r.id;
  end loop;
end
$$;

-- ---------- 2. a username is now required for every role ----------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_student_has_username;
alter table public.profiles drop constraint if exists profiles_has_username;
alter table public.profiles
  add constraint profiles_has_username
  check (username is not null);

-- ---------- 3. sign-up trigger: one rule for every role ------------------------------------------------------------------
-- The role still comes only from app_metadata (service role), never from what the browser sends. Whatever the role:
--   * a valid username is required, and the login address must be exactly <username>@certipass.invalid, so nobody
--     can register a real e-mail address;
--   * the profile never stores that internal address.
-- Public sign-ups are always students and are subject to the "registration closed" switch.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      public.user_role := 'student';
  v_meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_app       jsonb := coalesce(new.raw_app_meta_data, '{}'::jsonb);
  v_open      boolean;
  v_by_admin  boolean := coalesce(v_app ->> 'provisioned', 'false') = 'true';
  v_username  text;
  -- must match INTERNAL_EMAIL_DOMAIN in src/lib/identity.ts and the admin-create-user function
  v_internal_domain constant text := 'certipass.invalid';
begin
  if (v_app ->> 'role') in ('faculty', 'admin') then
    v_role := (v_app ->> 'role')::public.user_role;
  end if;

  v_username := lower(trim(coalesce(v_meta ->> 'username', '')));
  if v_username !~ '^(?=.{3,100}$)(?!.*\.\.)[a-z0-9]([a-z0-9._-]*[a-z0-9])?(@[a-z0-9]([a-z0-9._-]*[a-z0-9])?)?$' then
    raise exception 'Choose a username of 3 to 100 characters: letters, numbers, dots, dashes, underscores and at most one @.';
  end if;
  -- the "@" of an e-mail-style username is written "+" in the login address (usernames can't contain "+")
  if lower(coalesce(new.email, '')) <> replace(v_username, '@', '+') || '@' || v_internal_domain then
    raise exception 'Invalid sign-up request.';
  end if;

  if v_role = 'student' then
    if not v_by_admin then
      select coalesce((value #>> '{}')::boolean, true) into v_open
        from public.app_settings where key = 'allow_student_registration';
      if v_open is false then
        raise exception 'Student registration is currently closed.';
      end if;
    end if;
  end if;

  -- official-looking names are for the first administrator only (created by `npm run create-admin`)
  if v_role <> 'admin' and public.is_reserved_username(v_username) then
    raise exception 'That username is reserved. Please choose another.';
  end if;

  insert into public.profiles (
    id, role, username, full_name, email, register_number, faculty_id, department_id,
    year, section, designation, phone
  )
  values (
    new.id,
    v_role,
    v_username,
    coalesce(nullif(trim(v_meta ->> 'full_name'), ''), v_username),
    null, -- the internal login address is never stored
    case when v_role = 'student' then nullif(trim(v_meta ->> 'register_number'), '') end,
    case when v_role <> 'student' then nullif(trim(v_meta ->> 'faculty_id'), '') end,
    case when v_role <> 'admin' then nullif(v_meta ->> 'department_id', '')::uuid end,
    case when v_role = 'student' then nullif(v_meta ->> 'year', '')::smallint end,
    case when v_role = 'student' then nullif(trim(v_meta ->> 'section'), '') end,
    case when v_role = 'faculty' then nullif(trim(v_meta ->> 'designation'), '') end,
    nullif(trim(v_meta ->> 'phone'), '')
  );

  return new;
end;
$$;
